"""Generate the local service credentials and split them across three env files by who may hold them.

    .env.local   every process, including the session process (lawyers, THEMIS, judges):
                 API keys, config path, the app MongoDB user, Qdrant read-only key, Redis.
    .env.sealed  only offline and post-verdict processes (clerk, ingestion, evaluator, reflection):
                 the sealed MongoDB user and the Qdrant write key. Never loaded by a session process.
    .env.docker  only docker compose: root credentials and the server side of every key. Never loaded by Python.

Lines in .env.local that this script does not manage (API keys, comments) are kept verbatim.
Fresh passwords are generated unless --keep is given, which reuses values already present.

Usage: .venv/Scripts/python scripts/make_env.py [--keep]
After changing passwords, recreate the service volumes: docker compose --env-file .env.docker down -v
"""

from __future__ import annotations

import argparse
import secrets
from pathlib import Path

from dotenv import dotenv_values

ROOT = Path(__file__).resolve().parent.parent
LOCAL, SEALED, DOCKER = ROOT / ".env.local", ROOT / ".env.sealed", ROOT / ".env.docker"
MANAGED_PREFIXES = ("LEXARENA_MONGO_", "LEXARENA_QDRANT_", "LEXARENA_REDIS_")
HOST = "127.0.0.1"


def _secret() -> str:
    return secrets.token_hex(24)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--keep", action="store_true", help="reuse existing passwords and keys where present")
    args = parser.parse_args()

    old: dict[str, str] = {}
    for path in (LOCAL, SEALED, DOCKER):
        if path.exists():
            old.update({k: v for k, v in dotenv_values(path).items() if v})

    def value(name: str, default: str) -> str:
        return old.get(name, default) if args.keep else default

    app_db, sealed_db = "lexarena", "lexarena_sealed"
    server = {
        "LEXARENA_MONGO_ROOT_USER": "lexarena_root",
        "LEXARENA_MONGO_ROOT_PASSWORD": value("LEXARENA_MONGO_ROOT_PASSWORD", _secret()),
        "LEXARENA_MONGO_APP_DB": app_db,
        "LEXARENA_MONGO_APP_USER": "lexarena_app",
        "LEXARENA_MONGO_APP_PASSWORD": value("LEXARENA_MONGO_APP_PASSWORD", _secret()),
        "LEXARENA_MONGO_SEALED_DB": sealed_db,
        "LEXARENA_MONGO_SEALED_USER": "lexarena_sealed",
        "LEXARENA_MONGO_SEALED_PASSWORD": value("LEXARENA_MONGO_SEALED_PASSWORD", _secret()),
        "LEXARENA_QDRANT_SERVER_API_KEY": value("LEXARENA_QDRANT_SERVER_API_KEY", _secret()),
        "LEXARENA_QDRANT_SERVER_READ_ONLY_API_KEY": value("LEXARENA_QDRANT_SERVER_READ_ONLY_API_KEY", _secret()),
        "LEXARENA_REDIS_PASSWORD": value("LEXARENA_REDIS_PASSWORD", _secret()),
    }
    port = {"mongo": 27017, "qdrant": 6333, "redis": 6379}  # literal-ok: docker-compose.yml port bindings
    s = server
    local_managed = {
        "LEXARENA_MONGO_APP_DB": app_db,
        "LEXARENA_MONGO_APP_URI": (
            f"mongodb://{s['LEXARENA_MONGO_APP_USER']}:{s['LEXARENA_MONGO_APP_PASSWORD']}"
            f"@{HOST}:{port['mongo']}/{app_db}?authSource={app_db}"
        ),
        "LEXARENA_QDRANT_URL": f"http://{HOST}:{port['qdrant']}",
        "LEXARENA_QDRANT_READ_ONLY_API_KEY": s["LEXARENA_QDRANT_SERVER_READ_ONLY_API_KEY"],
        "LEXARENA_REDIS_URL": f"redis://:{s['LEXARENA_REDIS_PASSWORD']}@{HOST}:{port['redis']}/0",
    }
    sealed = {
        "LEXARENA_MONGO_SEALED_DB": sealed_db,
        "LEXARENA_MONGO_SEALED_URI": (
            f"mongodb://{s['LEXARENA_MONGO_SEALED_USER']}:{s['LEXARENA_MONGO_SEALED_PASSWORD']}"
            f"@{HOST}:{port['mongo']}/{sealed_db}?authSource={sealed_db}"
        ),
        "LEXARENA_QDRANT_WRITE_API_KEY": s["LEXARENA_QDRANT_SERVER_API_KEY"],
    }

    kept: list[str] = []
    if LOCAL.exists():
        for line in LOCAL.read_text(encoding="utf-8").splitlines():
            name = line.split("=", 1)[0].strip()
            if name.startswith(MANAGED_PREFIXES) or line.startswith("# Local services"):
                continue
            kept.append(line)
    while kept and not kept[-1].strip():
        kept.pop()

    def block(title: str, values: dict[str, str]) -> str:
        return "\n".join([title, *(f"{k}={v}" for k, v in values.items())]) + "\n"

    LOCAL.write_text(
        "\n".join(kept) + "\n\n" + block("# Local services (generated by scripts/make_env.py)", local_managed),
        encoding="utf-8",
    )
    SEALED.write_text(
        block("# Never loaded by a session process. Generated by scripts/make_env.py", sealed), encoding="utf-8"
    )
    DOCKER.write_text(
        block("# Read only by docker compose. Generated by scripts/make_env.py", server), encoding="utf-8"
    )
    for path, values in ((LOCAL, local_managed), (SEALED, sealed), (DOCKER, server)):
        print(f"{path.name}: {', '.join(values)}")


if __name__ == "__main__":
    main()
